Added documentation for reset, reset_code, and update. Updated some imagery in the unity package.
CyberHubXR/Docs pull request #5
Opened 2024-07-23 23:27 UTC by worth12

May be some grammar mistakes, but I tried to resolve any I could find.

2024-07-23 23:28 UTC, worth12 reviewed
Also, added general tab section to unity database manager section.

2024-07-25 19:12 UTC, WireWhiz requested changes
Looking really good, looks like there's one TODO that slipped through the cracks. Also looks like there's a broken link in `/docs/foundry/database-server/overview` to `/docs/foundry/unity-packages/database/overview`, I'm not seeing that in your changes so I think I was the one that broke that, but let's get it fixed so that CI runs.

2024-07-25 19:12 UTC, WireWhiz commented on docs/foundry/database-server/api.md
>  `// TODO`
Looks like we still have a TODO here, let's get that taken care of

2024-07-25 22:48 UTC, worth12 commented
Both are taken care of.

2024-07-29 16:24 UTC, merged